### ISSUE TITLE
Notice of invalid key sometimes being thrown

### ISSUE THREAD

**Issue by ddelrio1986** [justintadlock/cleaner-gallery#11]
The cleaner_gallery_get_setting function will sometimes throw a notice if you're trying to access a $option that is not found in the $settings array returned from the get_option function.

**Comment by ddelrio1986** [comment]
#2 is for this issue.

**Comment by justintadlock** [comment]
In `cleaner_gallery_get_setting()`, I need to do something like this:

```
$settings = get_option( 'cleaner_gallery_settings', cleaner_gallery_default_settings() );

$settings = wp_parse_args( $settings, cleaner_gallery_default_settings() );
```
